version: "3.8"

# persistence for gem deps
volumes:
  bundle:

services:
  ruby:
    build: .
    image: ruby-loc
    command: rails server --pid /tmp/foo.pid -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
